services:
  canute-car-rental-api:
    build:
      context: apps/canute-car-rental-api
      dockerfile: Dockerfile.dev
    container_name: canute-car-rental-api
    working_dir: /workspace/apps/canute-car-rental-api
    volumes:
      - .:/workspace
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    networks:
      - monorepo-thorfin

  einar-flight-api:
    build:
      context: apps/einar-flight-api
      dockerfile: Dockerfile.dev
    container_name: einar-flight-api
    working_dir: /workspace/apps/einar-flight-api
    volumes:
      - .:/workspace
    ports:
      - '3002:3000'
    depends_on:
      - postgres
    networks:
      - monorepo-thorfin

  leif-hotel-api:
    build:
      context: apps/leif-hotel-api
      dockerfile: Dockerfile.dev
    container_name: leif-hotel-api
    working_dir: /workspace/apps/leif-hotel-api
    volumes:
      - .:/workspace
    ports:
      - '3003:3000'
    depends_on:
      - postgres
    networks:
      - monorepo-thorfin

  thors-payment-api:
    build:
      context: apps/thors-payment-api
      dockerfile: Dockerfile.dev
    container_name: thors-payment-api
    working_dir: /workspace/apps/thors-payment-api
    volumes:
      - .:/workspace
    ports:
      - '3004:3000'
    depends_on:
      - postgres
    networks:
      - monorepo-thorfin

  postgres:
    image: postgres:15.15-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thorfinn
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monorepo-thorfin

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - monorepo-thorfin

  debezium-connect:
    image: debezium/connect:2.7.3.Final
    container_name: debezium-connect
    environment:
      - BOOTSTRAP_SERVERS=broker:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    ports:
      - '8083:8083'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8083/']
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - broker
      - postgres
    networks:
      - monorepo-thorfin
  register-connector:
    image: curlimages/curl
    depends_on:
      debezium-connect:
        condition: service_healthy
    volumes:
      - ./config.sh:/config.sh
    entrypoint: ['sh', '/config.sh']
    networks:
      - monorepo-thorfin

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    networks:
      - monorepo-thorfin

networks:
  monorepo-thorfin:

volumes:
  pgdata:
